description: WWM Insignia Docs & Guides
properties:
  - id: O7Csf
    name: Scope
    type: Many
    options:
      docportalVisible: true
    style: black
    icon: album
    values:
      - Корневой раздел
      - Главная
      - PVP
  - id: pyxNc
    name: Расписание_ГВГ_День
    type: Text
    style: orange-red
  - id: maLMd
    name: Расписание_ГВГ_Время
    type: Text
    style: orange-red
supportedLanguages: []
syntax: XML
title: WWM Insignia Docs
