description: WWM Insignia Docs & Guides
properties:
  - icon: album
    id: O7Csf
    name: Scope
    options:
      docportalVisible: true
    style: black
    type: Many
    values:
      - Корневой раздел
      - Главная
      - PVP События/Задания
      - PVE События/Задания
      - PVP Гайды
supportedLanguages: []
syntax: XML
title: WWM Insignia Docs
