description: WWM Insignia Docs & Guides
properties:
  - id: O7Csf
    name: Scope
    type: Many
    options:
      docportalVisible: true
    style: black
    icon: album
    values:
      - Корневой раздел
      - Главная
      - PVP
supportedLanguages: []
syntax: XML
title: WWM Insignia Docs
